# Configure relative paths for script execution
rawdataDir: rawdata
procdataDir: procdata
metadataDir: metadata
resultsDir: results
scriptsDir: scripts
logsDir: logs

# Configure Data URLs
metadata:
  sampleAnnotation: "https://data.broadinstitute.org/ccle/Cell_lines_annotations_20181226.txt"
  treatmentAnnotation: "https://data.broadinstitute.org/ccle_legacy_data/pharmacological_profiling/CCLE_NP24.2009_profiling_2012.02.20.csv"

treatmentResponse:
  GNF:
    description: "GNF drug sensitivity data. NOT USED YET."
    url: "https://data.broadinstitute.org/ccle_legacy_data/pharmacological_profiling/CCLE_GNF_data_090613.xls"
  doseResponse:
    description: "Dose response data"
    url: "https://data.broadinstitute.org/ccle_legacy_data/pharmacological_profiling/CCLE_NP24.2009_Drug_data_2015.02.24.csv"


# Configure Gencode genome parameters
ccle_gencode_ver: 19
gencode_reference: GRCh37

molecularProfiles:
  expression:
    rsem-genes_tpm: 
      description: "RNA-seq gene expression data. TPM values are log2 transformed."
      url: "https://data.broadinstitute.org/ccle/CCLE_RNAseq_rsem_genes_tpm_20180929.txt.gz"
    rsem-transcripts_tpm: 
      description: TODO::(add description)
      url: "https://data.broadinstitute.org/ccle/CCLE_RNAseq_rsem_transcripts_tpm_20180929.txt.gz"
    genes_counts: 
      description: TODO::(add description)
      url: "https://data.broadinstitute.org/ccle/CCLE_RNAseq_genes_counts_20180929.gct.gz"

  mutation:
    oncomapAssay: 
      description: TODO::(add description)
      url: "https://data.broadinstitute.org/ccle_legacy_data/oncomap_mutations/CCLE_Oncomap3_Assays_2012-04-09.csv"
    oncomap: 
      description: TODO::(add description)
      url: "https://data.broadinstitute.org/ccle_legacy_data/oncomap_mutations/CCLE_Oncomap3_2012-04-09.maf"
    hybridCapture:
      description: TODO::(add description)
      url: "https://data.broadinstitute.org/ccle_legacy_data/hybrid_capture_sequencing/CCLE_hybrid_capture1650_hg19_NoCommonSNPs_NoNeutralVariants_CDS_2012.05.07.maf"

  methylation:
    RBBS_TSS1kb:
      description: TODO::(add description)
      url: "https://data.broadinstitute.org/ccle/CCLE_RRBS_TSS1kb_20181022.txt.gz"

  cnv:
    copynumber_byGene: 
      description: TODO::(add description)
      url: "https://data.broadinstitute.org/ccle_legacy_data/dna_copy_number/CCLE_copynumber_byGene_2013-12-03.txt.gz"
      
    SNParrays:
      description: TODO::(add description)
      url: https://data.broadinstitute.org/ccle_legacy_data/dna_copy_number/CCLE_SNP.Arrays_2012-10-30_1.tar.gz
      url2: https://data.broadinstitute.org/ccle_legacy_data/dna_copy_number/CCLE_SNP.Arrays_2012-10-30_2.tar.gz
      url3: https://data.broadinstitute.org/ccle_legacy_data/dna_copy_number/CCLE_SNP.Arrays_2012-10-30_3.tar.gz
      url4: https://data.broadinstitute.org/ccle_legacy_data/dna_copy_number/CCLE_SNP.Arrays_2012-10-30_4.tar.gz
      metadata: https://data.broadinstitute.org/ccle_legacy_data/dna_copy_number/CCLE_SNP.Arrays.sif_2013-12-03.txt
      annotation:
        description: "Annotations correspond to hg18 (NCBI 36.1)"
        bioconductorPackage: "pd.genomewidesnp.6"