import React, {useState, useEffect, useContext} from 'react';
import { Button } from 'primereact/button';
import { AuthContext } from '../../../hooks/Context';
import useDatasetSearch from '../../../hooks/useDatasetSearch';
import SearchReqContext from '../SearchReqContext';

import {dataTypes} from '../../Shared/Enums';
import StyledPage from '../../../styles/StyledPage';
import { LayoutContainer, StyledContainer, StyledTopBar } from './Styles/StyledRadiomicSetSearch'

const RadiomicSetSearch = () => {
    
    const auth = useContext(AuthContext);
    const { searchAll, search } = useDatasetSearch(dataTypes.radiomics);
    
    const [datasets, setDatasets] = useState([]);
    const [selectedDatasets, setSelectedDatasets] = useState([]);
    const [isRequest, setIsRequest] = useState(false);
    
    const [parameters, setParameters] = useState({
        dataset: [],
        search: false
    });

    const [ready, setReady] = useState(false);

    useEffect(() => {
        const initializeView = async () => {
            const res = await search({...parameters, status: 'complete', private: false});
            console.log(res)
            setDatasets(res);
            setReady(true);
        }
        initializeView();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {   
        async function searchRadiomicSet() {
            console.log(parameters);
            let copy = JSON.parse(JSON.stringify(parameters));
            copy.dataset = copy.dataset.map(item => item.name);
            const result = await search({...copy, status: 'complete', private: false});
            setDatasets(result);
        }

        if(parameters.search){
            searchRadiomicSet();
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [parameters]);

    const showMessage = (status, data) => {
        let severity = status ? 'success' : 'error';
        RadiomicSetSearch.messages.show({severity: severity, summary: data.summary, detail: data.message, sticky: true});
        setSelectedDatasets([]);
    }
        
    return(
        <SearchReqContext.Provider 
            value={{ 
                parameters: parameters, 
                setParameters: setParameters, 
                isRequest: isRequest, 
                setIsRequest: setIsRequest
            }}
        >
            <StyledPage style={{marginBottom: "20px", width: "80%" }}>
				<StyledTopBar>
					<h1 className="title">
						RADCURE
					</h1>
				</StyledTopBar>
				<LayoutContainer>
					<div className="content-row">
						<StyledContainer style={{width: "40%"}}>
							<div class="card-container">
								<div class="card-title">
									About The Dataset
								</div>
								<div className='hr-container'>
									<hr className='hr-style'/>
								</div>
								<div className='subsection'>
									<h2>
										Description
									</h2>
									<p className='description'>
										{'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis' +
										'in faucibus orci luctus et ultrices posuere cubilia curae; Morbi porttitor felis nec elit' +
										'sollicitudin, sed lacinia massa tempor. Pellentesque ac orci a lorem efficitur.'}
									</p>
								</div>
								<div className='subsection'>
									<h2>
										General Information
									</h2>
									<ul className='list-style-card-main'>
										<li><span>Generated By:</span> BHK lab</li>
										<li><span>Curated By:</span> BHK lab</li>
										<li><span>Curated On:</span> MM-DD-YYYY</li>
										<li><span>Useful Links:</span>
											<ul className='list-style-card-sub'>
												<li>Link 1: https://github.com</li>
												<li>Link 2: https://google.com</li>
												<li>Link 3: https://youtube.com</li>
											</ul>
										</li>
									</ul>
								</div>
								<div className='subsection'>
									<h2>
										Technical Information
									</h2>
									<ul className='list-style-card-main'>
										<li><span>DOI:</span> 10.5281/zenodo.8332910</li>
										<li><span>Format:</span> rds file</li>
										<li><span>Version:</span> RADCURE 2023</li>
										<li><span>License:</span> Users must abide by the TCIA Data Usage Policy and Restrictions.</li>
									</ul>
								</div>
								<div className='subsection'>
									<h2>
										Disclaimers
									</h2>
									<p className='description'>
										<span>Data Disclaimer: </span>
										{'The Cleveland data was generated and shared by the Broad Institute CTD^2 Center.' + 
										'The Haibe-Kains Lab has re-annotated the data to maximize overlap with other radiogenomic datasets.'}
									</p>
									<p className='description'>
										<span>Data Usage Policy: </span>
										{'The CTD^2 releases data in accordance with their data release policy.'}
									</p>
									<p className='description'>
										<span>Please Cite the Following: </span>
										{'Multi-institutional Prognostic Modeling in Head and Neck Cancer: ' +
										'Evaluating Impact and Generalizability of Deep Learning and Radiomics. Cancer Research Communications 1 ' + 
										'June 2023; 3 (6): 1140–1151. https://doi.org/10.1158/2767-9764.CRC-22-0152'}
									</p>
								</div>
							</div>
						</StyledContainer>

						<StyledContainer>
							<div class="card-container">
								<div class="card-title ">Dataset Specifics</div>
								<div className='hr-container'>
									<hr className='hr-style'/>
								</div>
								<div className='subsection'>
									<h2>
										RNA Seq
									</h2>
									<ul className='list-style-card-main'>
										<li><span>{'Raw Data Source(s)'}:</span>
											<ul className='list-style-card-sub'>
												<li>Data Source 1: https://NCBI.com</li>
												<li>Data Source 2: https://github.com</li>
												<li>Data Source 3: https://EGA.com</li>
											</ul>
										</li>
										<li><span>Processing Tools:</span> Kalisto, ...</li>
										<li><span>Data Transformation:</span> Lorem ipsum dolor sit amet</li>
										<li><span>Gencode Version:</span> Lorem ipsum dolor sit amet</li>
									</ul>
								</div>
								<div className='subsection'>
									<h2>DNA Seq</h2>
									<ul className='list-style-card-main'>
										<li><span>{'Raw Data Source(s)'}:</span>
											<ul className='list-style-card-sub'>
												<li>Data Source 1: https://NCBI.com</li>
												<li>Data Source 2: https://github.com</li>
												<li>Data Source 3: https://EGA.com</li>
											</ul>
										</li>
										<li><span>Processing Tools:</span> tool 1, tool 2</li>
										<li><span>Data Transformation:</span> Lorem ipsum dolor sit amet</li>
										<li><span>Gencode Version:</span> Lorem ipsum dolor sit amet</li>
									</ul>
								</div>
								<div className='subsection'>
									<h2>Drug Response</h2>
									<ul className='list-style-card-main'>
										<li><span>{'Raw Data Source(s)'}:</span>
											<ul className='list-style-card-sub'>
												<li>Data Source 1: https://NCBI.com</li>
												<li>Data Source 2: https://github.com</li>
												<li>Data Source 3: https://EGA.com</li>
											</ul>
										</li>
										<li><span>Processing Method:</span> ComputeAAC</li>
										<li><span>Recist Availability:</span> Lorem ipsum dolor sit amet</li>
									</ul>
								</div>
							</div>
						</StyledContainer>

						<StyledContainer>
							<div class="card-container">
								<div class="card-title ">Pipeline Information</div>
								<div className='hr-container'>
									<hr className='hr-style'/>
								</div>
								<h2>Pipeline Details</h2>
								<ul className='list-style-card-main'>
									<li><span>Pipeline:</span> https://github.com/bhklab/RADCURE</li>
									<li><span>Docker Image:</span> https://hub.docker.com/r/minorunakano/orcestra-snakemake</li>
									<li><span>{'Data Curation Script(s)'}:</span>
										<ul className='list-style-card-sub'>
											<li>Data Source 1: https://github.com/bhklab/script1</li>
											<li>Data Source 2: https://github.com/bhklab/script2</li>
											<li>Data Source 3: https://github.com/bhklab/script3</li>
										</ul>
									</li>
								</ul>
								<h2>Release Notes</h2>
								<ul className='list-style-card-main'>
									<li><span>Samples:</span> 2949 samples in this dataset</li>
									<li><span>Primary Tumours:</span> 2988 primary tumours in this dataset</li>
									<li><span>Added Samples:</span> 450 samples were added in this iteration</li>
								</ul>
								<h2>Badges</h2>
								<ul className='list-style-card-main'>
									<li><span>Annotations Standards:</span> Lorem ipsum dolor sit amet</li>
									<li><span>QC scripts or CO capsule:</span> https://codeocean.com</li>
								</ul>
							</div>
							<div className='button-container'>
								<Button className="download-button" icon='pi pi-download' label="Download BioCompute Object" />
								<Button className="download-button" icon='pi pi-download' label="Download Dataset" />
							</div>
						</StyledContainer>
					</div>
				</LayoutContainer>
            </StyledPage>
        </SearchReqContext.Provider>
    );
}

export default RadiomicSetSearch;