import React, {useState, useEffect, useContext} from 'react';
import { Button } from 'primereact/button';
import { AuthContext } from '../../../hooks/Context';
import useDatasetSearch from '../../../hooks/useDatasetSearch';
import SearchReqContext from '../SearchReqContext';

import {dataTypes} from '../../Shared/Enums';
import StyledPage from '../../../styles/StyledPage';
import { LayoutContainer, StyledContainerOuter, StyledContainerInner, StyledTopBar } from './Styles/StyledRadiomicSetSearch'

const RadiomicSetSearch = () => {
    
    const auth = useContext(AuthContext);
    const { searchAll, search } = useDatasetSearch(dataTypes.radiomics);
    
    const [datasets, setDatasets] = useState([]);
    const [selectedDatasets, setSelectedDatasets] = useState([]);
    const [isRequest, setIsRequest] = useState(false);
    
    const [parameters, setParameters] = useState({
        dataset: [],
        search: false
    });

    const [ready, setReady] = useState(false);

    useEffect(() => {
        const initializeView = async () => {
            const res = await search({...parameters, status: 'complete', private: false});
            console.log(res)
            setDatasets(res);
            setReady(true);
        }
        initializeView();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {   
        async function searchRadiomicSet() {
            console.log(parameters);
            let copy = JSON.parse(JSON.stringify(parameters));
            copy.dataset = copy.dataset.map(item => item.name);
            const result = await search({...copy, status: 'complete', private: false});
            setDatasets(result);
        }

        if(parameters.search){
            searchRadiomicSet();
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [parameters]);

    const showMessage = (status, data) => {
        let severity = status ? 'success' : 'error';
        RadiomicSetSearch.messages.show({severity: severity, summary: data.summary, detail: data.message, sticky: true});
        setSelectedDatasets([]);
    }
        
    return(
        <SearchReqContext.Provider 
            value={{ 
                parameters: parameters, 
                setParameters: setParameters, 
                isRequest: isRequest, 
                setIsRequest: setIsRequest
            }}
        >
            <StyledPage>
				<StyledTopBar>
					<h1 className="title">
						RADCURE
					</h1>
					<Button className="download-button" icon='pi pi-download' label="Download Dataset" />
				</StyledTopBar>
				<LayoutContainer>
					<div className="content-row">
						<StyledContainerOuter>
							<div class="card-container">
								<div class="card-title ">Description</div>
								<hr className='hr-style'/>
									{'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis' +
									'in faucibus orci luctus et ultrices posuere cubilia curae; Morbi porttitor felis nec elit' +
									'sollicitudin, sed lacinia massa tempor. Pellentesque ac orci a lorem efficitur.'}
							</div>
							<div class="card-container">
								<div class="card-title ">About The Dataset</div>
								<hr className='hr-style'/>
								<ul className='list-style-card-main'>
									<li><span>Generated By:</span> BHK lab</li>
									<li><span>Curated By:</span> BHK lab</li>
									<li><span>Curated On:</span> MM-DD-YYYY</li>
									<li><span>Useful Links:</span>
										<ul className='list-style-card-sub'>
											<li>Link 1: https://github.com</li>
											<li>Link 2: https://google.com</li>
											<li>Link 3: https://youtube.com</li>
										</ul>
									</li>
								</ul>
							</div>
							<div class="card-container">
								<div class="card-title ">Technical Information</div>
								<hr className='hr-style'/>
								<ul className='list-style-card-main'>
									<li><span>DOI:</span> 10.5281/zenodo.8332910</li>
									<li><span>Format:</span> rds file</li>
									<li><span>Version:</span> RADCURE 2023</li>
									<li><span>License:</span> Users must abide by the TCIA Data Usage Policy and Restrictions.</li>
								</ul>
							</div>
						</StyledContainerOuter>

						<StyledContainerInner>
							<div class="card-container">
								<div class="card-title ">RNA Seq</div>
								<ul className='list-style-card-main'>
									<li><span>{'Raw Data Source(s)'}:</span>
										<ul className='list-style-card-sub'>
											<li>Data Source 1: https://NCBI.com</li>
											<li>Data Source 2: https://github.com</li>
											<li>Data Source 3: https://EGA.com</li>
										</ul>
									</li>
									<li><span>Processing Tools:</span> Kalisto, ...</li>
									<li><span>Data Transformation:</span> Lorem ipsum dolor sit amet</li>
									<li><span>Gencode Version:</span> Lorem ipsum dolor sit amet</li>
								</ul>
							</div>
							<div class="card-container">
								<div class="card-title ">DNA Seq</div>
								<ul className='list-style-card-main'>
									<li><span>{'Raw Data Source(s)'}:</span>
										<ul className='list-style-card-sub'>
											<li>Data Source 1: https://NCBI.com</li>
											<li>Data Source 2: https://github.com</li>
											<li>Data Source 3: https://EGA.com</li>
										</ul>
									</li>
									<li><span>Processing Tools:</span> tool 1, tool 2</li>
									<li><span>Data Transformation:</span> Lorem ipsum dolor sit amet</li>
									<li><span>Gencode Version:</span> Lorem ipsum dolor sit amet</li>
								</ul>
							</div>
							<div class="card-container">
								<div class="card-title ">Drug Response</div>
								<ul className='list-style-card-main'>
									<li><span>{'Raw Data Source(s)'}:</span>
										<ul className='list-style-card-sub'>
											<li>Data Source 1: https://NCBI.com</li>
											<li>Data Source 2: https://github.com</li>
											<li>Data Source 3: https://EGA.com</li>
										</ul>
									</li>
									<li><span>Processing Method:</span> ComputeAAC</li>
									<li><span>Recist Availability:</span> Lorem ipsum dolor sit amet</li>
								</ul>
							</div>
						</StyledContainerInner>

						<StyledContainerOuter>
							<div class="card-container">
								<div class="card-title ">Pipeline Details</div>
								<ul className='list-style-card-main'>
									<li><span>Pipeline:</span> https://github.com/bhklab/RADCURE</li>
									<li><span>Docker Image:</span> https://hub.docker.com/r/minorunakano/orcestra-snakemake</li>
									<li><span>{'Data Curation Script(s)'}:</span>
										<ul className='list-style-card-sub'>
											<li>Data Source 1: https://github.com/bhklab/script1</li>
											<li>Data Source 2: https://github.com/bhklab/script2</li>
											<li>Data Source 3: https://github.com/bhklab/script3</li>
										</ul>
									</li>
								</ul>
							</div>
							<div class="card-container">
								<div class="card-title ">Release Notes</div>
								<ul className='list-style-card-main'>
									<li><span>Samples:</span> 2949 samples in this dataset</li>
									<li><span>Primary Tumours:</span> 2988 primary tumours in this dataset</li>
									<li><span>Added Samples:</span> 450 samples were added in this iteration</li>
								</ul>
							</div>
							<div class="card-container">
								<div class="card-title ">Badges</div>
								<ul className='list-style-card-main'>
									<li><span>Annotations Standards:</span> Lorem ipsum dolor sit amet</li>
									<li><span>QC scripts or CO capsule:</span> https://codeocean.com</li>
								</ul>
							</div>
						</StyledContainerOuter>
					</div>
				</LayoutContainer>
            </StyledPage>
        </SearchReqContext.Provider>
    );
}

export default RadiomicSetSearch;