import React, {useState, useEffect, useContext} from 'react';
import { Button } from 'primereact/button';
import { AuthContext } from '../../../hooks/Context';
import useDatasetSearch from '../../../hooks/useDatasetSearch';
import SearchReqContext from '../SearchReqContext';

import {dataTypes} from '../../Shared/Enums';
import StyledPage from '../../../styles/StyledPage';
import { LayoutContainer, StyledContainerOuter, StyledContainerInner, StyledTopBar } from './Styles/StyledRadiomicSetSearch'
import * as MainStyle from '../../Main/MainStyle';

const RadiomicSetSearch = () => {
    
    const auth = useContext(AuthContext);
    const { searchAll, search } = useDatasetSearch(dataTypes.radiomics);
    
    const [datasets, setDatasets] = useState([]);
    const [selectedDatasets, setSelectedDatasets] = useState([]);
    const [isRequest, setIsRequest] = useState(false);
    
    const [parameters, setParameters] = useState({
        dataset: [],
        search: false
    });

    const [ready, setReady] = useState(false);

    useEffect(() => {
        const initializeView = async () => {
            const res = await search({...parameters, status: 'complete', private: false});
            console.log(res)
            setDatasets(res);
            setReady(true);
        }
        initializeView();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {   
        async function searchRadiomicSet() {
            console.log(parameters);
            let copy = JSON.parse(JSON.stringify(parameters));
            copy.dataset = copy.dataset.map(item => item.name);
            const result = await search({...copy, status: 'complete', private: false});
            setDatasets(result);
        }

        if(parameters.search){
            searchRadiomicSet();
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [parameters]);

    const showMessage = (status, data) => {
        let severity = status ? 'success' : 'error';
        RadiomicSetSearch.messages.show({severity: severity, summary: data.summary, detail: data.message, sticky: true});
        setSelectedDatasets([]);
    }
        
    return(
        <SearchReqContext.Provider 
            value={{ 
                parameters: parameters, 
                setParameters: setParameters, 
                isRequest: isRequest, 
                setIsRequest: setIsRequest
            }}
        >
            <StyledPage>
				<StyledTopBar>
					<h1 className="title">
						CCLE 2019
					</h1>
					<MainStyle.Button className="download-button" icon='pi pi-download' label="Download Dataset" />
				</StyledTopBar>
				<LayoutContainer>
					<div className="content-row">
						<StyledContainerOuter>
							<div class="card-container">
								<div class="card-title ">Description</div>
								<div className='hr-container'>
									<hr className='hr-style'/>
								</div>
									{'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis' +
									'in faucibus orci luctus et ultrices posuere cubilia curae; Morbi porttitor felis nec elit' +
									'sollicitudin, sed lacinia massa tempor. Pellentesque ac orci a lorem efficitur.'}
							</div>
							<div class="card-container">
								<div class="card-title ">About The Dataset</div>
								<div className='hr-container'>
									<hr className='hr-style'/>
								</div>
								<ul className='list-style-card-main'>
									<li><span>Generated By:</span> BHK lab</li>
									<li><span>Curated By:</span> BHK lab</li>
									<li><span>Curated On:</span> 01-01-2024</li>
									<li><span>DOI:</span> 10.5281/zenodo.8332910</li>
									<li><span>Format:</span> rds file</li>
									<li><span>Version:</span> CCLE 2019</li>
									<li><span>License:</span> Users must abide by the TCIA Data Usage Policy and Restrictions.</li>
									<li><span>Data Disclaimer: </span>
										The Cleveland data was generated and shared by the Broad Institute CTD^2 Center. 
										The Haibe-Kains Lab has re-annotated the data to maximize overlap with other radiogenomic datasets.
									</li>
									<li><span>Data Usage Policy: </span>
										The CTD^2 releases data in accordance with their data release policy.
									</li>
									<li><span>Please Cite the Following: </span>
										Multi-institutional Prognostic Modeling in Head and Neck Cancer:
										Evaluating Impact and Generalizability of Deep Learning and Radiomics. Cancer Research Communications 1
										June 2023; 3 (6): 1140–1151. https://doi.org/10.1158/2767-9764.CRC-22-0152
									</li>
									<li><span>Useful Links:</span>
										<ul className='list-style-card-sub'>
											<li>Link 1: https://github.com</li>
											<li>Link 2: https://google.com</li>
										</ul>
									</li>
								</ul>
							</div>
						</StyledContainerOuter>

						<StyledContainerInner>
							<div class="card-container">
								<div class="card-title ">RNA Seq</div>
								<div className='hr-container'>
									<hr className='hr-style'/>
								</div>
								<ul className='list-style-card-main'>
									<li><span>Expressions:</span>	
										<ul className='list-style-card-sub'>
											<li>
												<a href='https://data.broadinstitute.org/ccle/CCLE_RNAseq_rsem_genes_tpm_20180929.txt.gz' target='_blank'>
													<span>Source 1:</span>
												</a>
												{` RNA-seq gene expression data. TPM values are log2 transformed.`}
											</li>
											<li>
												<a href='https://data.broadinstitute.org/ccle/CCLE_RNAseq_rsem_transcripts_tpm_20180929.txt.gz' target='_blank'>
													<span>Source 2:</span>
												</a>
												{` TODO::(add description)`}
											</li>
											<li>
												<a href='https://data.broadinstitute.org/ccle/CCLE_RNAseq_genes_counts_20180929.gct.gz' target='_blank'>
													<span>Source 3:</span>
												</a>
												{` TODO::(add description)`}
											</li>
										</ul>
									</li>
									<li><span>Mutations:</span>
										
										<ul className='list-style-card-sub'>
											<li>
												<a href='https://data.broadinstitute.org/ccle_legacy_data/oncomap_mutations/CCLE_Oncomap3_Assays_2012-04-09.csv' target='_blank'>
													<span>Source 1:</span>
												</a>
												{` TODO::(add description)`}
											</li>
											<li>
												<a href='https://data.broadinstitute.org/ccle_legacy_data/oncomap_mutations/CCLE_Oncomap3_2012-04-09.maf' target='_blank'>
													<span>Source 2:</span>
												</a>
												{` TODO::(add description)`}
											</li>
											<li>
												<a href='https://data.broadinstitute.org/ccle_legacy_data/hybrid_capture_sequencing/CCLE_hybrid_capture1650_hg19_NoCommonSNPs_NoNeutralVariants_CDS_2012.05.07.maf' target='_blank'>
													<span>Source 3:</span>
												</a>
												{` TODO::(add description)`}
											</li>
										</ul>
									</li>
									<li><span>Methylation:</span>	
										<ul className='list-style-card-sub'>
											<li>
												<a href='https://data.broadinstitute.org/ccle_legacy_data/hybrid_capture_sequencing/CCLE_hybrid_capture1650_hg19_NoCommonSNPs_NoNeutralVariants_CDS_2012.05.07.maf' target='_blank'>
													<span>Source 1:</span>
												</a>
												{` TODO::(add description)`}
											</li>
										</ul>
									</li>
									<li><span>CNV:</span>
										<ul className='list-style-card-sub'>
											<li>
												<a href='https://data.broadinstitute.org/ccle_legacy_data/oncomap_mutations/CCLE_Oncomap3_Assays_2012-04-09.csv' target='_blank'>
													<span>Source 1:</span>
												</a>
												{` TODO::(add description)`}
											</li>
										</ul>
										<ul className='list-style-card-sub'>
											<li>
												<a href='https://data.broadinstitute.org/ccle_legacy_data/dna_copy_number/CCLE_SNP.Arrays_2012-10-30_1.tar.gz' target='_blank'>
													<span>Source 2:</span>
												</a>
												{` TODO::(add description)`}
											</li>
											<ul className='list-style-card-info'>
												<li>
													<a href='https://data.broadinstitute.org/ccle_legacy_data/dna_copy_number/CCLE_SNP.Arrays_2012-10-30_1.tar.gz' target='_blank'>
														<span>Metadata</span>
													</a>
												</li>
												<li>
													<span>Annotation:</span>
													{' Annotations correspond to hg18 (NCBI 36.1). pd.genomewidesnp.6'}
												</li>
											</ul>
										</ul>	
									</li>
								</ul>
							</div>
							{/* <div class="card-container">
								<div class="card-title ">DNA Seq</div>
								<div className='hr-container'>
									<hr className='hr-style'/>
								</div>
								<ul className='list-style-card-main'>
									<li><span>Raw Data Source(s):</span>
										<ul className='list-style-card-sub'>
											<li>Source 1: https://NCBI.com</li>
											<li>Source 2: https://github.com</li>
											<li>Source 3: https://EGA.com</li>
										</ul>
									</li>
									<li><span>Processing Tools:</span> tool 1, tool 2</li>
									<li><span>Data Transformation:</span> Lorem ipsum dolor sit amet</li>
									<li><span>Gencode Version:</span> Lorem ipsum dolor sit amet</li>
								</ul>
							</div> */}
							<div class="card-container">
								<div class="card-title ">Drug Response</div>
								<div className='hr-container'>
									<hr className='hr-style'/>
								</div>
								<ul className='list-style-card-main'>
									<li><span>GNF:</span>	
										<ul className='list-style-card-sub'>
											<li>
												<span>Source 1:</span>
												<ul className='list-style-card-info'>
													<li>
														<span>
															Description:
														</span>
														{' Description: GNF drug sensitivity data. NOT USED YET.'}
													</li>
													<li>
														<a href='https://data.broadinstitute.org/ccle_legacy_data/pharmacological_profiling/CCLE_GNF_data_090613.xls' target='_blank'>
															<span>
																Download link
															</span>
														</a>
													</li>
													
												</ul>
											</li>
										</ul>
									</li>
									<li><span>Dose Response:</span>	
										<ul className='list-style-card-sub'>
											<li>
												<span>Source 1:</span>
												<ul className='list-style-card-info'>
													<li>
														<span>
															Description:
														</span>
														{' Dose response data.'}
													</li>
													<li>
														<a href='https://data.broadinstitute.org/ccle_legacy_data/pharmacological_profiling/CCLE_NP24.2009_Drug_data_2015.02.24.csv' target='_blank'>
															<span>
																Download link
															</span>
														</a>
													</li>
													
												</ul>
											</li>
										</ul>
									</li>
								</ul>
							</div>
						</StyledContainerInner>

						<StyledContainerOuter>
							<div class="card-container">
								<div class="card-title ">Pipeline Details</div>
								<div className='hr-container'>
									<hr className='hr-style'/>
								</div>
								<ul className='list-style-card-main'>
									<li><span>Pipeline:</span> https://github.com/bhklab/CCLE_2019</li>
									<li><span>Docker Image:</span> https://hub.docker.com/r/minorunakano/orcestra-snakemake</li>
									<li><span>{'Data Curation Script(s)'}:</span>
										<ul className='list-style-card-sub'>
											<li>Source 1: https://github.com/bhklab/script1</li>
											<li>Source 2: https://github.com/bhklab/script2</li>
											<li>Source 3: https://github.com/bhklab/script3</li>
										</ul>
									</li>
									<li><span>Processing Tools:</span> Kalisto, ...</li>
									<li><span>Gencode Version:</span>GRCh37</li>
									<li><span>Data Transformation:</span>?</li>
								</ul>
							</div>
							<div class="card-container">
								<div class="card-title ">Release Notes</div>
								<div className='hr-container'>
									<hr className='hr-style'/>
								</div>
								<ul className='list-style-card-main'>
									<li><span>Samples:</span> 2949 samples in this dataset</li>
									<li><span>Primary Tumours:</span> 2988 primary tumours in this dataset</li>
									<li><span>Added Samples:</span> 450 samples were added in this iteration</li>
								</ul>
							</div>
							<div class="card-container">
								<div class="card-title ">Badges</div>
								<div className='hr-container'>
									<hr className='hr-style'/>
								</div>
								<ul className='list-style-card-main'>
									<li><span>Annotations Standards:</span> Lorem ipsum dolor sit amet</li>
									<li><span>QC scripts or CO capsule:</span> https://codeocean.com</li>
								</ul>
							</div>
						</StyledContainerOuter>
					</div>
				</LayoutContainer>
            </StyledPage>
        </SearchReqContext.Provider>
    );
}

export default RadiomicSetSearch;